/// Flutter icons CustomIcons
/// Copyright (C) 2026 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
///
library;

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData arrowDown = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowUp = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrowForward = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData driverChat = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bankDetails = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookingId = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData call = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cash = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chatWithAdmin = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData copy = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData debit = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData description = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData driverOnWay = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData driverPickup = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropLocation = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData edit = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData email = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emergencyContact = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData feedback = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filledRemove = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hailRide = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData inviteFriend = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData livechat = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationRadius = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manageAccount = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manageInformation = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manufactureName = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modelName = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData modelYear = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myEarning = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myPreferences = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myWallet = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData name = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigation = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notification = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData onlinePayment = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData orderId = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paymentMethod = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paymentStatus = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData discountPercent = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pickupLocation = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData manageAddress = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rating = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ratingMenu = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reachedDestination = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radiusFilter = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData referHistory = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData referralCode = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData remove = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reportIssue = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rideDatetime = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rideHistory = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scheduleRide = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData selectContact = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sos = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stopPoint = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData swipe = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ticketId = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vehicleColor = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData verifiedUser = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fingerprint = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setOnMap = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData findDriver = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData workAddress = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData homeAddress = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData otherAddress = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData deleteBin = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData removeFilled = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heatMap = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vehicleInformation = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData drivingLicence = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData editDate = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uploadImage = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData imageIcon = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bankName = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menuIconDots = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backButton = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locationTime = IconData(0xe8c1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
