/// National mobile number length rules per ISO country code.
/// Derived from libphonenumber metadata; Colombia enforces exact 10 digits starting with 3.
class PhoneLengthRule {
  const PhoneLengthRule({
    required this.min,
    required this.max,
    this.exact = false,
    this.pattern,
  });

  final int min;
  final int max;
  final bool exact;
  final RegExp? pattern;

  bool isValidLength(int length) {
    if (exact) return length == min;
    return length >= min && length <= max;
  }

  bool matchesPattern(String digits) {
    if (pattern == null) return true;
    return pattern!.hasMatch(digits);
  }
}

const PhoneLengthRule _defaultRule = PhoneLengthRule(min: 6, max: 15);

final Map<String, PhoneLengthRule> _rulesByIso = {
  'AC': PhoneLengthRule(min: 5, max: 5, exact: true),
  'AD': PhoneLengthRule(min: 6, max: 9),
  'AE': PhoneLengthRule(min: 8, max: 9),
  'AF': PhoneLengthRule(min: 9, max: 9, exact: true),
  'AG': PhoneLengthRule(min: 10, max: 10, exact: true),
  'AI': PhoneLengthRule(min: 10, max: 10, exact: true),
  'AL': PhoneLengthRule(min: 8, max: 9),
  'AM': PhoneLengthRule(min: 8, max: 8, exact: true),
  'AO': PhoneLengthRule(min: 9, max: 9, exact: true),
  'AR': PhoneLengthRule(min: 10, max: 11),
  'AS': PhoneLengthRule(min: 10, max: 10, exact: true),
  'AT': PhoneLengthRule(min: 4, max: 13),
  'AU': PhoneLengthRule(min: 9, max: 9, exact: true),
  'AW': PhoneLengthRule(min: 7, max: 7, exact: true),
  'AX': PhoneLengthRule(min: 6, max: 10),
  'AZ': PhoneLengthRule(min: 9, max: 9, exact: true),
  'BA': PhoneLengthRule(min: 8, max: 9),
  'BB': PhoneLengthRule(min: 10, max: 10, exact: true),
  'BD': PhoneLengthRule(min: 6, max: 10),
  'BE': PhoneLengthRule(min: 8, max: 9),
  'BF': PhoneLengthRule(min: 8, max: 8, exact: true),
  'BG': PhoneLengthRule(min: 6, max: 9),
  'BH': PhoneLengthRule(min: 8, max: 8, exact: true),
  'BI': PhoneLengthRule(min: 8, max: 8, exact: true),
  'BJ': PhoneLengthRule(min: 10, max: 10, exact: true),
  'BL': PhoneLengthRule(min: 9, max: 9, exact: true),
  'BM': PhoneLengthRule(min: 10, max: 10, exact: true),
  'BN': PhoneLengthRule(min: 7, max: 7, exact: true),
  'BO': PhoneLengthRule(min: 8, max: 8, exact: true),
  'BQ': PhoneLengthRule(min: 7, max: 7, exact: true),
  'BR': PhoneLengthRule(min: 10, max: 11),
  'BS': PhoneLengthRule(min: 10, max: 10, exact: true),
  'BT': PhoneLengthRule(min: 7, max: 8),
  'BW': PhoneLengthRule(min: 7, max: 8),
  'BY': PhoneLengthRule(min: 9, max: 9, exact: true),
  'BZ': PhoneLengthRule(min: 7, max: 7, exact: true),
  'CA': PhoneLengthRule(min: 10, max: 10, exact: true),
  'CC': PhoneLengthRule(min: 9, max: 9, exact: true),
  'CD': PhoneLengthRule(min: 7, max: 10),
  'CF': PhoneLengthRule(min: 8, max: 8, exact: true),
  'CG': PhoneLengthRule(min: 9, max: 9, exact: true),
  'CH': PhoneLengthRule(min: 9, max: 9, exact: true),
  'CI': PhoneLengthRule(min: 10, max: 10, exact: true),
  'CK': PhoneLengthRule(min: 5, max: 5, exact: true),
  'CL': PhoneLengthRule(min: 9, max: 9, exact: true),
  'CM': PhoneLengthRule(min: 9, max: 9, exact: true),
  'CN': PhoneLengthRule(min: 7, max: 11),
  'CO': PhoneLengthRule(min: 10, max: 10, exact: true, pattern: RegExp(r'^3[0-9]{9}$')),
  'CR': PhoneLengthRule(min: 8, max: 8, exact: true),
  'CU': PhoneLengthRule(min: 6, max: 10),
  'CV': PhoneLengthRule(min: 7, max: 7, exact: true),
  'CW': PhoneLengthRule(min: 7, max: 8),
  'CX': PhoneLengthRule(min: 9, max: 9, exact: true),
  'CY': PhoneLengthRule(min: 8, max: 8, exact: true),
  'CZ': PhoneLengthRule(min: 9, max: 9, exact: true),
  'DE': PhoneLengthRule(min: 5, max: 15),
  'DJ': PhoneLengthRule(min: 8, max: 8, exact: true),
  'DK': PhoneLengthRule(min: 8, max: 8, exact: true),
  'DM': PhoneLengthRule(min: 10, max: 10, exact: true),
  'DO': PhoneLengthRule(min: 10, max: 10, exact: true),
  'DZ': PhoneLengthRule(min: 8, max: 9),
  'EC': PhoneLengthRule(min: 8, max: 9),
  'EE': PhoneLengthRule(min: 7, max: 8),
  'EG': PhoneLengthRule(min: 8, max: 10),
  'EH': PhoneLengthRule(min: 9, max: 9, exact: true),
  'ER': PhoneLengthRule(min: 7, max: 7, exact: true),
  'ES': PhoneLengthRule(min: 9, max: 9, exact: true),
  'ET': PhoneLengthRule(min: 9, max: 9, exact: true),
  'FI': PhoneLengthRule(min: 5, max: 10),
  'FJ': PhoneLengthRule(min: 7, max: 7, exact: true),
  'FK': PhoneLengthRule(min: 5, max: 5, exact: true),
  'FM': PhoneLengthRule(min: 7, max: 7, exact: true),
  'FO': PhoneLengthRule(min: 6, max: 6, exact: true),
  'FR': PhoneLengthRule(min: 9, max: 9, exact: true),
  'GA': PhoneLengthRule(min: 7, max: 8),
  'GB': PhoneLengthRule(min: 9, max: 10),
  'GD': PhoneLengthRule(min: 10, max: 10, exact: true),
  'GE': PhoneLengthRule(min: 9, max: 9, exact: true),
  'GF': PhoneLengthRule(min: 9, max: 9, exact: true),
  'GG': PhoneLengthRule(min: 10, max: 10, exact: true),
  'GH': PhoneLengthRule(min: 9, max: 9, exact: true),
  'GI': PhoneLengthRule(min: 8, max: 8, exact: true),
  'GL': PhoneLengthRule(min: 6, max: 6, exact: true),
  'GM': PhoneLengthRule(min: 7, max: 7, exact: true),
  'GN': PhoneLengthRule(min: 8, max: 9),
  'GP': PhoneLengthRule(min: 9, max: 9, exact: true),
  'GQ': PhoneLengthRule(min: 9, max: 9, exact: true),
  'GR': PhoneLengthRule(min: 10, max: 10, exact: true),
  'GT': PhoneLengthRule(min: 8, max: 8, exact: true),
  'GU': PhoneLengthRule(min: 10, max: 10, exact: true),
  'GW': PhoneLengthRule(min: 9, max: 9, exact: true),
  'GY': PhoneLengthRule(min: 7, max: 7, exact: true),
  'HK': PhoneLengthRule(min: 8, max: 8, exact: true),
  'HN': PhoneLengthRule(min: 8, max: 8, exact: true),
  'HR': PhoneLengthRule(min: 8, max: 9),
  'HT': PhoneLengthRule(min: 8, max: 8, exact: true),
  'HU': PhoneLengthRule(min: 8, max: 9),
  'ID': PhoneLengthRule(min: 7, max: 12),
  'IE': PhoneLengthRule(min: 7, max: 10),
  'IL': PhoneLengthRule(min: 8, max: 12),
  'IM': PhoneLengthRule(min: 10, max: 10, exact: true),
  'IN': PhoneLengthRule(min: 10, max: 10, exact: true),
  'IO': PhoneLengthRule(min: 7, max: 7, exact: true),
  'IQ': PhoneLengthRule(min: 8, max: 10),
  'IR': PhoneLengthRule(min: 6, max: 10),
  'IS': PhoneLengthRule(min: 7, max: 9),
  'IT': PhoneLengthRule(min: 6, max: 12),
  'JE': PhoneLengthRule(min: 10, max: 10, exact: true),
  'JM': PhoneLengthRule(min: 10, max: 10, exact: true),
  'JO': PhoneLengthRule(min: 8, max: 9),
  'JP': PhoneLengthRule(min: 9, max: 10),
  'KE': PhoneLengthRule(min: 7, max: 9),
  'KG': PhoneLengthRule(min: 9, max: 9, exact: true),
  'KH': PhoneLengthRule(min: 8, max: 9),
  'KI': PhoneLengthRule(min: 5, max: 8),
  'KM': PhoneLengthRule(min: 7, max: 7, exact: true),
  'KN': PhoneLengthRule(min: 10, max: 10, exact: true),
  'KP': PhoneLengthRule(min: 8, max: 10),
  'KR': PhoneLengthRule(min: 5, max: 10),
  'KW': PhoneLengthRule(min: 8, max: 8, exact: true),
  'KY': PhoneLengthRule(min: 10, max: 10, exact: true),
  'KZ': PhoneLengthRule(min: 10, max: 10, exact: true),
  'LA': PhoneLengthRule(min: 8, max: 10),
  'LB': PhoneLengthRule(min: 7, max: 8),
  'LC': PhoneLengthRule(min: 10, max: 10, exact: true),
  'LI': PhoneLengthRule(min: 7, max: 9),
  'LK': PhoneLengthRule(min: 9, max: 9, exact: true),
  'LR': PhoneLengthRule(min: 7, max: 9),
  'LS': PhoneLengthRule(min: 8, max: 8, exact: true),
  'LT': PhoneLengthRule(min: 8, max: 8, exact: true),
  'LU': PhoneLengthRule(min: 4, max: 11),
  'LV': PhoneLengthRule(min: 8, max: 8, exact: true),
  'LY': PhoneLengthRule(min: 9, max: 9, exact: true),
  'MA': PhoneLengthRule(min: 9, max: 9, exact: true),
  'MC': PhoneLengthRule(min: 8, max: 9),
  'MD': PhoneLengthRule(min: 8, max: 8, exact: true),
  'ME': PhoneLengthRule(min: 8, max: 8, exact: true),
  'MF': PhoneLengthRule(min: 9, max: 9, exact: true),
  'MG': PhoneLengthRule(min: 9, max: 9, exact: true),
  'MH': PhoneLengthRule(min: 7, max: 7, exact: true),
  'MK': PhoneLengthRule(min: 8, max: 8, exact: true),
  'ML': PhoneLengthRule(min: 8, max: 8, exact: true),
  'MM': PhoneLengthRule(min: 6, max: 10),
  'MN': PhoneLengthRule(min: 8, max: 10),
  'MO': PhoneLengthRule(min: 8, max: 8, exact: true),
  'MP': PhoneLengthRule(min: 10, max: 10, exact: true),
  'MQ': PhoneLengthRule(min: 9, max: 9, exact: true),
  'MR': PhoneLengthRule(min: 8, max: 8, exact: true),
  'MS': PhoneLengthRule(min: 10, max: 10, exact: true),
  'MT': PhoneLengthRule(min: 8, max: 8, exact: true),
  'MU': PhoneLengthRule(min: 7, max: 8),
  'MV': PhoneLengthRule(min: 7, max: 7, exact: true),
  'MW': PhoneLengthRule(min: 7, max: 9),
  'MX': PhoneLengthRule(min: 10, max: 10, exact: true),
  'MY': PhoneLengthRule(min: 8, max: 10),
  'MZ': PhoneLengthRule(min: 8, max: 9),
  'NA': PhoneLengthRule(min: 8, max: 9),
  'NC': PhoneLengthRule(min: 6, max: 6, exact: true),
  'NE': PhoneLengthRule(min: 8, max: 8, exact: true),
  'NF': PhoneLengthRule(min: 6, max: 6, exact: true),
  'NG': PhoneLengthRule(min: 10, max: 10, exact: true),
  'NI': PhoneLengthRule(min: 8, max: 8, exact: true),
  'NL': PhoneLengthRule(min: 9, max: 11),
  'NO': PhoneLengthRule(min: 8, max: 8, exact: true),
  'NP': PhoneLengthRule(min: 8, max: 10),
  'NR': PhoneLengthRule(min: 7, max: 7, exact: true),
  'NU': PhoneLengthRule(min: 4, max: 7),
  'NZ': PhoneLengthRule(min: 8, max: 10),
  'OM': PhoneLengthRule(min: 8, max: 8, exact: true),
  'PA': PhoneLengthRule(min: 7, max: 8),
  'PE': PhoneLengthRule(min: 8, max: 9),
  'PF': PhoneLengthRule(min: 8, max: 8, exact: true),
  'PG': PhoneLengthRule(min: 7, max: 8),
  'PH': PhoneLengthRule(min: 6, max: 10),
  'PK': PhoneLengthRule(min: 9, max: 10),
  'PL': PhoneLengthRule(min: 7, max: 9),
  'PM': PhoneLengthRule(min: 6, max: 9),
  'PR': PhoneLengthRule(min: 10, max: 10, exact: true),
  'PS': PhoneLengthRule(min: 8, max: 9),
  'PT': PhoneLengthRule(min: 9, max: 9, exact: true),
  'PW': PhoneLengthRule(min: 7, max: 7, exact: true),
  'PY': PhoneLengthRule(min: 7, max: 9),
  'QA': PhoneLengthRule(min: 8, max: 8, exact: true),
  'RE': PhoneLengthRule(min: 9, max: 9, exact: true),
  'RO': PhoneLengthRule(min: 6, max: 9),
  'RS': PhoneLengthRule(min: 7, max: 12),
  'RU': PhoneLengthRule(min: 10, max: 10, exact: true),
  'RW': PhoneLengthRule(min: 8, max: 9),
  'SA': PhoneLengthRule(min: 9, max: 9, exact: true),
  'SB': PhoneLengthRule(min: 5, max: 7),
  'SC': PhoneLengthRule(min: 7, max: 7, exact: true),
  'SD': PhoneLengthRule(min: 9, max: 9, exact: true),
  'SE': PhoneLengthRule(min: 7, max: 9),
  'SG': PhoneLengthRule(min: 8, max: 8, exact: true),
  'SH': PhoneLengthRule(min: 4, max: 5),
  'SI': PhoneLengthRule(min: 8, max: 8, exact: true),
  'SJ': PhoneLengthRule(min: 8, max: 8, exact: true),
  'SK': PhoneLengthRule(min: 6, max: 9),
  'SL': PhoneLengthRule(min: 8, max: 8, exact: true),
  'SM': PhoneLengthRule(min: 8, max: 10),
  'SN': PhoneLengthRule(min: 9, max: 9, exact: true),
  'SO': PhoneLengthRule(min: 6, max: 9),
  'SR': PhoneLengthRule(min: 6, max: 7),
  'SS': PhoneLengthRule(min: 9, max: 9, exact: true),
  'ST': PhoneLengthRule(min: 7, max: 7, exact: true),
  'SV': PhoneLengthRule(min: 8, max: 8, exact: true),
  'SX': PhoneLengthRule(min: 10, max: 10, exact: true),
  'SY': PhoneLengthRule(min: 8, max: 9),
  'SZ': PhoneLengthRule(min: 8, max: 8, exact: true),
  'TA': PhoneLengthRule(min: 4, max: 4, exact: true),
  'TC': PhoneLengthRule(min: 10, max: 10, exact: true),
  'TD': PhoneLengthRule(min: 8, max: 8, exact: true),
  'TG': PhoneLengthRule(min: 8, max: 8, exact: true),
  'TH': PhoneLengthRule(min: 8, max: 9),
  'TJ': PhoneLengthRule(min: 9, max: 9, exact: true),
  'TK': PhoneLengthRule(min: 4, max: 7),
  'TL': PhoneLengthRule(min: 7, max: 8),
  'TM': PhoneLengthRule(min: 8, max: 8, exact: true),
  'TN': PhoneLengthRule(min: 8, max: 8, exact: true),
  'TO': PhoneLengthRule(min: 5, max: 7),
  'TR': PhoneLengthRule(min: 10, max: 10, exact: true),
  'TT': PhoneLengthRule(min: 10, max: 10, exact: true),
  'TV': PhoneLengthRule(min: 5, max: 7),
  'TW': PhoneLengthRule(min: 8, max: 9),
  'TZ': PhoneLengthRule(min: 9, max: 9, exact: true),
  'UA': PhoneLengthRule(min: 9, max: 9, exact: true),
  'UG': PhoneLengthRule(min: 9, max: 9, exact: true),
  'US': PhoneLengthRule(min: 10, max: 10, exact: true),
  'UY': PhoneLengthRule(min: 8, max: 8, exact: true),
  'UZ': PhoneLengthRule(min: 9, max: 9, exact: true),
  'VA': PhoneLengthRule(min: 6, max: 11),
  'VC': PhoneLengthRule(min: 10, max: 10, exact: true),
  'VE': PhoneLengthRule(min: 10, max: 10, exact: true),
  'VG': PhoneLengthRule(min: 10, max: 10, exact: true),
  'VI': PhoneLengthRule(min: 10, max: 10, exact: true),
  'VN': PhoneLengthRule(min: 9, max: 10),
  'VU': PhoneLengthRule(min: 5, max: 7),
  'WF': PhoneLengthRule(min: 6, max: 6, exact: true),
  'WS': PhoneLengthRule(min: 5, max: 10),
  'XK': PhoneLengthRule(min: 8, max: 12),
  'YE': PhoneLengthRule(min: 7, max: 9),
  'YT': PhoneLengthRule(min: 9, max: 9, exact: true),
  'ZA': PhoneLengthRule(min: 5, max: 9),
  'ZM': PhoneLengthRule(min: 9, max: 9, exact: true),
  'ZW': PhoneLengthRule(min: 5, max: 10),
};

final Map<String, PhoneLengthRule> _rulesByDialCode = {
  '1': PhoneLengthRule(min: 10, max: 10, exact: true),
  '7': PhoneLengthRule(min: 10, max: 10, exact: true),
  '20': PhoneLengthRule(min: 8, max: 10),
  '27': PhoneLengthRule(min: 5, max: 9),
  '30': PhoneLengthRule(min: 10, max: 10, exact: true),
  '31': PhoneLengthRule(min: 9, max: 11),
  '32': PhoneLengthRule(min: 8, max: 9),
  '33': PhoneLengthRule(min: 9, max: 9, exact: true),
  '34': PhoneLengthRule(min: 9, max: 9, exact: true),
  '36': PhoneLengthRule(min: 8, max: 9),
  '39': PhoneLengthRule(min: 6, max: 12),
  '40': PhoneLengthRule(min: 6, max: 9),
  '41': PhoneLengthRule(min: 9, max: 9, exact: true),
  '43': PhoneLengthRule(min: 4, max: 13),
  '44': PhoneLengthRule(min: 10, max: 10, exact: true),
  '45': PhoneLengthRule(min: 8, max: 8, exact: true),
  '46': PhoneLengthRule(min: 7, max: 9),
  '47': PhoneLengthRule(min: 8, max: 8, exact: true),
  '48': PhoneLengthRule(min: 7, max: 9),
  '49': PhoneLengthRule(min: 5, max: 15),
  '51': PhoneLengthRule(min: 8, max: 9),
  '52': PhoneLengthRule(min: 10, max: 10, exact: true),
  '53': PhoneLengthRule(min: 6, max: 10),
  '54': PhoneLengthRule(min: 10, max: 11),
  '55': PhoneLengthRule(min: 10, max: 11),
  '56': PhoneLengthRule(min: 9, max: 9, exact: true),
  '57': PhoneLengthRule(min: 10, max: 10, exact: true, pattern: RegExp(r'^3[0-9]{9}$')),
  '58': PhoneLengthRule(min: 10, max: 10, exact: true),
  '60': PhoneLengthRule(min: 8, max: 10),
  '61': PhoneLengthRule(min: 9, max: 9, exact: true),
  '62': PhoneLengthRule(min: 7, max: 12),
  '63': PhoneLengthRule(min: 6, max: 10),
  '64': PhoneLengthRule(min: 8, max: 10),
  '65': PhoneLengthRule(min: 8, max: 8, exact: true),
  '66': PhoneLengthRule(min: 8, max: 9),
  '81': PhoneLengthRule(min: 9, max: 10),
  '82': PhoneLengthRule(min: 5, max: 10),
  '84': PhoneLengthRule(min: 9, max: 10),
  '86': PhoneLengthRule(min: 7, max: 11),
  '90': PhoneLengthRule(min: 10, max: 10, exact: true),
  '91': PhoneLengthRule(min: 10, max: 10, exact: true),
  '92': PhoneLengthRule(min: 9, max: 10),
  '93': PhoneLengthRule(min: 9, max: 9, exact: true),
  '94': PhoneLengthRule(min: 9, max: 9, exact: true),
  '95': PhoneLengthRule(min: 6, max: 10),
  '98': PhoneLengthRule(min: 6, max: 10),
  '211': PhoneLengthRule(min: 9, max: 9, exact: true),
  '212': PhoneLengthRule(min: 9, max: 9, exact: true),
  '213': PhoneLengthRule(min: 8, max: 9),
  '216': PhoneLengthRule(min: 8, max: 8, exact: true),
  '218': PhoneLengthRule(min: 9, max: 9, exact: true),
  '220': PhoneLengthRule(min: 7, max: 7, exact: true),
  '221': PhoneLengthRule(min: 9, max: 9, exact: true),
  '222': PhoneLengthRule(min: 8, max: 8, exact: true),
  '223': PhoneLengthRule(min: 8, max: 8, exact: true),
  '224': PhoneLengthRule(min: 8, max: 9),
  '225': PhoneLengthRule(min: 10, max: 10, exact: true),
  '226': PhoneLengthRule(min: 8, max: 8, exact: true),
  '227': PhoneLengthRule(min: 8, max: 8, exact: true),
  '228': PhoneLengthRule(min: 8, max: 8, exact: true),
  '229': PhoneLengthRule(min: 10, max: 10, exact: true),
  '230': PhoneLengthRule(min: 7, max: 8),
  '231': PhoneLengthRule(min: 7, max: 9),
  '232': PhoneLengthRule(min: 8, max: 8, exact: true),
  '233': PhoneLengthRule(min: 9, max: 9, exact: true),
  '234': PhoneLengthRule(min: 10, max: 10, exact: true),
  '235': PhoneLengthRule(min: 8, max: 8, exact: true),
  '236': PhoneLengthRule(min: 8, max: 8, exact: true),
  '237': PhoneLengthRule(min: 9, max: 9, exact: true),
  '238': PhoneLengthRule(min: 7, max: 7, exact: true),
  '239': PhoneLengthRule(min: 7, max: 7, exact: true),
  '240': PhoneLengthRule(min: 9, max: 9, exact: true),
  '241': PhoneLengthRule(min: 7, max: 8),
  '242': PhoneLengthRule(min: 9, max: 9, exact: true),
  '243': PhoneLengthRule(min: 7, max: 10),
  '244': PhoneLengthRule(min: 9, max: 9, exact: true),
  '245': PhoneLengthRule(min: 9, max: 9, exact: true),
  '246': PhoneLengthRule(min: 7, max: 7, exact: true),
  '248': PhoneLengthRule(min: 7, max: 7, exact: true),
  '249': PhoneLengthRule(min: 9, max: 9, exact: true),
  '250': PhoneLengthRule(min: 8, max: 9),
  '251': PhoneLengthRule(min: 9, max: 9, exact: true),
  '252': PhoneLengthRule(min: 6, max: 9),
  '253': PhoneLengthRule(min: 8, max: 8, exact: true),
  '254': PhoneLengthRule(min: 7, max: 9),
  '255': PhoneLengthRule(min: 9, max: 9, exact: true),
  '256': PhoneLengthRule(min: 9, max: 9, exact: true),
  '257': PhoneLengthRule(min: 8, max: 8, exact: true),
  '258': PhoneLengthRule(min: 8, max: 9),
  '260': PhoneLengthRule(min: 9, max: 9, exact: true),
  '261': PhoneLengthRule(min: 9, max: 9, exact: true),
  '262': PhoneLengthRule(min: 9, max: 9, exact: true),
  '263': PhoneLengthRule(min: 5, max: 10),
  '264': PhoneLengthRule(min: 8, max: 9),
  '265': PhoneLengthRule(min: 7, max: 9),
  '266': PhoneLengthRule(min: 8, max: 8, exact: true),
  '267': PhoneLengthRule(min: 7, max: 8),
  '268': PhoneLengthRule(min: 8, max: 8, exact: true),
  '269': PhoneLengthRule(min: 7, max: 7, exact: true),
  '290': PhoneLengthRule(min: 4, max: 5),
  '291': PhoneLengthRule(min: 7, max: 7, exact: true),
  '297': PhoneLengthRule(min: 7, max: 7, exact: true),
  '298': PhoneLengthRule(min: 6, max: 6, exact: true),
  '299': PhoneLengthRule(min: 6, max: 6, exact: true),
  '350': PhoneLengthRule(min: 8, max: 8, exact: true),
  '351': PhoneLengthRule(min: 9, max: 9, exact: true),
  '352': PhoneLengthRule(min: 4, max: 11),
  '353': PhoneLengthRule(min: 7, max: 10),
  '354': PhoneLengthRule(min: 7, max: 9),
  '355': PhoneLengthRule(min: 8, max: 9),
  '356': PhoneLengthRule(min: 8, max: 8, exact: true),
  '357': PhoneLengthRule(min: 8, max: 8, exact: true),
  '358': PhoneLengthRule(min: 6, max: 10),
  '359': PhoneLengthRule(min: 6, max: 9),
  '370': PhoneLengthRule(min: 8, max: 8, exact: true),
  '371': PhoneLengthRule(min: 8, max: 8, exact: true),
  '372': PhoneLengthRule(min: 7, max: 8),
  '373': PhoneLengthRule(min: 8, max: 8, exact: true),
  '374': PhoneLengthRule(min: 8, max: 8, exact: true),
  '375': PhoneLengthRule(min: 9, max: 9, exact: true),
  '376': PhoneLengthRule(min: 6, max: 9),
  '377': PhoneLengthRule(min: 8, max: 9),
  '378': PhoneLengthRule(min: 8, max: 10),
  '379': PhoneLengthRule(min: 6, max: 11),
  '380': PhoneLengthRule(min: 9, max: 9, exact: true),
  '381': PhoneLengthRule(min: 7, max: 12),
  '382': PhoneLengthRule(min: 8, max: 8, exact: true),
  '383': PhoneLengthRule(min: 8, max: 12),
  '385': PhoneLengthRule(min: 8, max: 9),
  '386': PhoneLengthRule(min: 8, max: 8, exact: true),
  '387': PhoneLengthRule(min: 8, max: 9),
  '389': PhoneLengthRule(min: 8, max: 8, exact: true),
  '420': PhoneLengthRule(min: 9, max: 9, exact: true),
  '421': PhoneLengthRule(min: 6, max: 9),
  '423': PhoneLengthRule(min: 7, max: 9),
  '500': PhoneLengthRule(min: 5, max: 5, exact: true),
  '501': PhoneLengthRule(min: 7, max: 7, exact: true),
  '502': PhoneLengthRule(min: 8, max: 8, exact: true),
  '503': PhoneLengthRule(min: 8, max: 8, exact: true),
  '504': PhoneLengthRule(min: 8, max: 8, exact: true),
  '505': PhoneLengthRule(min: 8, max: 8, exact: true),
  '506': PhoneLengthRule(min: 8, max: 8, exact: true),
  '507': PhoneLengthRule(min: 7, max: 8),
  '508': PhoneLengthRule(min: 6, max: 9),
  '509': PhoneLengthRule(min: 8, max: 8, exact: true),
  '590': PhoneLengthRule(min: 9, max: 9, exact: true),
  '591': PhoneLengthRule(min: 8, max: 8, exact: true),
  '592': PhoneLengthRule(min: 7, max: 7, exact: true),
  '593': PhoneLengthRule(min: 8, max: 9),
  '594': PhoneLengthRule(min: 9, max: 9, exact: true),
  '595': PhoneLengthRule(min: 7, max: 9),
  '596': PhoneLengthRule(min: 9, max: 9, exact: true),
  '597': PhoneLengthRule(min: 6, max: 7),
  '598': PhoneLengthRule(min: 8, max: 8, exact: true),
  '670': PhoneLengthRule(min: 7, max: 8),
  '672': PhoneLengthRule(min: 6, max: 6, exact: true),
  '673': PhoneLengthRule(min: 7, max: 7, exact: true),
  '674': PhoneLengthRule(min: 7, max: 7, exact: true),
  '675': PhoneLengthRule(min: 7, max: 8),
  '676': PhoneLengthRule(min: 5, max: 7),
  '677': PhoneLengthRule(min: 5, max: 7),
  '678': PhoneLengthRule(min: 5, max: 7),
  '679': PhoneLengthRule(min: 7, max: 7, exact: true),
  '680': PhoneLengthRule(min: 7, max: 7, exact: true),
  '681': PhoneLengthRule(min: 6, max: 6, exact: true),
  '682': PhoneLengthRule(min: 5, max: 5, exact: true),
  '683': PhoneLengthRule(min: 4, max: 7),
  '685': PhoneLengthRule(min: 5, max: 10),
  '686': PhoneLengthRule(min: 5, max: 8),
  '687': PhoneLengthRule(min: 6, max: 6, exact: true),
  '688': PhoneLengthRule(min: 5, max: 7),
  '689': PhoneLengthRule(min: 8, max: 8, exact: true),
  '690': PhoneLengthRule(min: 4, max: 7),
  '691': PhoneLengthRule(min: 7, max: 7, exact: true),
  '692': PhoneLengthRule(min: 7, max: 7, exact: true),
  '850': PhoneLengthRule(min: 8, max: 10),
  '852': PhoneLengthRule(min: 8, max: 8, exact: true),
  '853': PhoneLengthRule(min: 8, max: 8, exact: true),
  '855': PhoneLengthRule(min: 8, max: 9),
  '856': PhoneLengthRule(min: 8, max: 10),
  '868': PhoneLengthRule(min: 10, max: 10, exact: true),
  '880': PhoneLengthRule(min: 6, max: 10),
  '886': PhoneLengthRule(min: 8, max: 9),
  '960': PhoneLengthRule(min: 7, max: 7, exact: true),
  '961': PhoneLengthRule(min: 7, max: 8),
  '962': PhoneLengthRule(min: 8, max: 9),
  '963': PhoneLengthRule(min: 8, max: 9),
  '964': PhoneLengthRule(min: 8, max: 10),
  '965': PhoneLengthRule(min: 8, max: 8, exact: true),
  '966': PhoneLengthRule(min: 9, max: 9, exact: true),
  '967': PhoneLengthRule(min: 7, max: 9),
  '968': PhoneLengthRule(min: 8, max: 8, exact: true),
  '970': PhoneLengthRule(min: 8, max: 9),
  '971': PhoneLengthRule(min: 8, max: 9),
  '972': PhoneLengthRule(min: 8, max: 12),
  '973': PhoneLengthRule(min: 8, max: 8, exact: true),
  '974': PhoneLengthRule(min: 8, max: 8, exact: true),
  '975': PhoneLengthRule(min: 7, max: 8),
  '976': PhoneLengthRule(min: 8, max: 10),
  '977': PhoneLengthRule(min: 8, max: 10),
  '992': PhoneLengthRule(min: 9, max: 9, exact: true),
  '993': PhoneLengthRule(min: 8, max: 8, exact: true),
  '994': PhoneLengthRule(min: 9, max: 9, exact: true),
  '995': PhoneLengthRule(min: 9, max: 9, exact: true),
  '996': PhoneLengthRule(min: 9, max: 9, exact: true),
  '998': PhoneLengthRule(min: 9, max: 9, exact: true),
};

PhoneLengthRule phoneLengthRuleForDialCode(String? dialCode, {String? isoCode}) {
  if (isoCode != null && isoCode.isNotEmpty) {
    final byIso = _rulesByIso[isoCode.toUpperCase()];
    if (byIso != null) return byIso;
  }
  final digits = dialCode?.replaceAll(RegExp(r'\D'), '') ?? '';
  if (digits.isEmpty) return _rulesByIso['CO'] ?? _defaultRule;
  return _rulesByDialCode[digits] ?? _defaultRule;
}

int phoneMaxInputLength(String? dialCode, {String? isoCode}) {
  return phoneLengthRuleForDialCode(dialCode, isoCode: isoCode).max;
}
